apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask-app
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 5000        # Service port
    targetPort: 5000  # Container port
    nodePort: 30080   # External port (30000-32767 range for NodePort)
    name: http
